version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run pre-commit
          command: make lint
      - run:
          name: Build package
          command: make dist

  unit-tests:
    parameters:
      python:
        type: string
    executor:
      name: python/default
      tag: <<parameters.python>>
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Unit Test
          command: make test
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: coverage.xml
          destination: coverage-reports

  deploy-test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Upload to PyPI
          command: |
            poetry config repositories.test-pypi https://test.pypi.org/legacy/
            poetry publish --build -r test-pypi -u $PYPI_TEST_USER -p $PYPI_TEST_PASSWORD

  deploy-production:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Upload to PyPI
          command: poetry publish --build -u $PYPI_PROD_USER -p $PYPI_PROD_PASSWORD

workflows:
  test:
    jobs:
      - build
      - unit-tests:
          requires:
            - build
          matrix:
            parameters:
              python: ["3.8", "3.9", "3.10", "3.11", "3.12"]
  tag:
    jobs:
      - deploy-test:
          context: sceptre-templates-context
          filters:
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
            branches:
              ignore: /.*/
      - deploy-production:
          context: sceptre-templates-context
          requires:
            - deploy-test
          filters:
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
            branches:
              ignore: /.*/
